# Generated by Django 5.2.7 on 2025-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите текст записи", null=True, verbose_name="Содержимое блога"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blog/photo/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("is_publication", models.BooleanField(default=False, verbose_name="Опубликовано")),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Автоматически увеличивается при просмотре",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
                "ordering": ["-created_at"],
            },
        ),
    ]
