# Generated by Django 5.2.7 on 2025-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/photo/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Стоимость продукта",
                max_digits=10,
                verbose_name="Цена продукта",
            ),
        ),
    ]
