# Generated by Django 5.2.7 on 2025-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_picture_alter_product_purchase_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Отметьте, чтобы опубликовать продукт", verbose_name="Опубликовать продукт"
            ),
        ),
    ]
